formatter: "markdown table"

version: ""

header-from: main.tf
footer-from: ""

sections:
  hide: []
  show: []

content: |-
  # terraform-kubernetes-helm-charts
  
  [![official JetBrains project](https://jb.gg/badges/official.svg)](https://confluence.jetbrains.com/display/ALL/JetBrains+on+GitHub)
  
  This module allows to deploy at least one Helm Chart in a Kubernetes cluster.

  ## Status

  Work in progress.

  ## Features

  * Allows installing a list of Helm Charts;

  * Allows injecting custom values.yaml configurations that will override the default chart's configurations;

  * Allows injecting only a few parameters that will override the default chart's configuration;

  * Allows injecting secrets in a sensitive manner;

  ## Core concepts

  * [What is Kubernetes?](https://kubernetes.io/docs/home/);

  * [What is the Helm Provider for Kubernetes](https://registry.terraform.io/providers/hashicorp/helm/latest/docs);

  * [How is configured the Helm Provider in this Module](https://registry.terraform.io/providers/hashicorp/helm/latest/docs#exec-plugins).

  ## Examples

  For how-to examples, please refer to the [examples](./examples) directory.

  {{ .Requirements }}
  {{ .Providers }}
  {{ .Resources }}
  {{ .Inputs }}
  {{ .Outputs }}

output:
  file: "README.md"
  mode: replace

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
