name: Module Releaser

on:
  push:
    branches:
      - main

jobs:
  call-tag-workflow:
    uses: JetBrains/actions/.github/workflows/tag.yaml@main
    secrets: inherit
  call-changelog-workflow:
    uses: JetBrains/actions/.github/workflows/changelog.yaml@main
    secrets: inherit
