name: Tag

on:
  push:
    branches:
      - main
    paths:
      - '**/*.tf'
      - '!examples/**'

jobs:
  call-tag-workflow:
    uses: JetBrains/actions/.github/workflows/tag.yaml@main
    secrets: inherit
